In [2]:
import pandas as pd
import numpy as np
from pandas.io.json import json_normalize
import json
import matplotlib.pyplot as plt
%matplotlib inline
import warnings
import matplotlib.patches as patches
warnings.filterwarnings("ignore")
from mplsoccer.pitch import Pitch
plt.style.use('ggplot')
from PIL import Image
from highlight_text import htext
from matplotlib import cm
import matplotlib.patheffects as path_effects

In [129]:
with open(r"Lyon_Toulouse.json") as f:
    md = json.load(f)

In [130]:
pd.set_option('display.max_columns', None)
# pd.set_option('display.max_rows', None)

In [131]:
df = json_normalize(md["events"], sep="_")

In [132]:
df.isGoal.value_counts()

True    3
Name: isGoal, dtype: int64

In [133]:
df.isGoal.value_counts()

True    3
Name: isGoal, dtype: int64

In [140]:
df['Assist'] = df['isGoal'].shift(-3)

In [141]:
mask1 = df['Assist'] == True
df.loc[mask1]

,eventId,expandedMinute,id,isTouch,minute,qualifiers,satisfiedEventsTypes,second,teamId,x,y,outcomeType_displayName,outcomeType_value,period_displayName,period_value,type_displayName,type_value,endX,endY,playerId,goalMouthY,goalMouthZ,isShot,relatedEventId,relatedPlayerId,blockedX,blockedY,isGoal,cardType_displayName,cardType_value,$idx,$len,field,satisfiers,text,minuteInfo_expandedMinute,minuteInfo_extraTime,minuteInfo_isEndOfPeriod,minuteInfo_minute,minuteInfo_minuteString,minuteInfo_period,type_$idx,type_$len,Assist
474,308,28,2178992941,True,28,"[{'type': {'displayName': 'RegularPlay', 'valu...","[90, 91, 118, 116, 122, 123, 126, 204, 38, 45,...",7.0,228,49.4,33.0,Successful,1,FirstHalf,1,Pass,1,72.0,87.4,322096.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
1291,807,74,2179031589,True,70,"[{'type': {'displayName': 'BlockedX', 'value':...","[90, 8, 9, 2, 3, 12]",41.0,228,79.9,68.8,Successful,1,SecondHalf,2,SavedShot,15,NaN,NaN,121718.0,52.2,12.7,True,NaN,NaN,97.5,52.3,NaN,NaN,NaN,16.0,20.0,1.0,"[{'$idx': 0, '$len': 6, 'id': 90, 'name': 'tou...","Mar√ßal has attempt saved (Low to the left, Out...",74.0,0.0,False,70,71,2,NaN,NaN,True
1363,845,80,2179034793,False,76,[],[92],8.0,228,78.2,36.6,Successful,1,SecondHalf,2,BallRecovery,49,NaN,NaN,140090.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True

In [142]:
mask = (df['playerId'] == 322096) & (df['Assist'] == True)
aouar = df.loc[mask]
aouar

,eventId,expandedMinute,id,isTouch,minute,qualifiers,satisfiedEventsTypes,second,teamId,x,y,outcomeType_displayName,outcomeType_value,period_displayName,period_value,type_displayName,type_value,endX,endY,playerId,goalMouthY,goalMouthZ,isShot,relatedEventId,relatedPlayerId,blockedX,blockedY,isGoal,cardType_displayName,cardType_value,$idx,$len,field,satisfiers,text,minuteInfo_expandedMinute,minuteInfo_extraTime,minuteInfo_isEndOfPeriod,minuteInfo_minute,minuteInfo_minuteString,minuteInfo_period,type_$idx,type_$len,Assist
474,308,28,2178992941,True,28,"[{'type': {'displayName': 'RegularPlay', 'valu...","[90, 91, 118, 116, 122, 123, 126, 204, 38, 45,...",7.0,228,49.4,33.0,Successful,1,FirstHalf,1,Pass,1,72.0,87.4,322096.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True

In [143]:
aouar.to_csv('Lyon_Toulouse1.csv', index=False)

In [144]:
import os
import glob
import pandas as pd
import seaborn as sns

In [145]:
extension = 'csv'
all_filenames = [i for i in glob.glob('*.{}'.format(extension))]

#combine all files in the list
combined_csv = pd.concat([pd.read_csv(f) for f in all_filenames ])
#export to csv
combined_csv.to_csv( "aouar_all1.csv", index=False, encoding='utf-8-sig')